/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScanSessionIdRouteImport } from './routes/scan.$sessionId'
import { Route as AuthenticatedSetupRouteImport } from './routes/_authenticated/setup'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSalesRouteImport } from './routes/_authenticated/sales'
import { Route as AuthenticatedRestaurantRouteImport } from './routes/_authenticated/restaurant'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedRepairRouteImport } from './routes/_authenticated/repair'
import { Route as AuthenticatedPurchasesRouteImport } from './routes/_authenticated/purchases'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedPosRouteImport } from './routes/_authenticated/pos'
import { Route as AuthenticatedManufacturingRouteImport } from './routes/_authenticated/manufacturing'
import { Route as AuthenticatedHrmRouteImport } from './routes/_authenticated/hrm'
import { Route as AuthenticatedFilesRouteImport } from './routes/_authenticated/files'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings.index'
import { Route as AuthenticatedRestaurantIndexRouteImport } from './routes/_authenticated/restaurant.index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports.index'
import { Route as AuthenticatedRepairIndexRouteImport } from './routes/_authenticated/repair.index'
import { Route as AuthenticatedProductsIndexRouteImport } from './routes/_authenticated/products.index'
import { Route as AuthenticatedHrmIndexRouteImport } from './routes/_authenticated/hrm.index'
import { Route as AuthenticatedCrmIndexRouteImport } from './routes/_authenticated/crm.index'
import { Route as AuthenticatedSettingsUsersRouteImport } from './routes/_authenticated/settings.users'
import { Route as AuthenticatedSettingsUnitsRouteImport } from './routes/_authenticated/settings.units'
import { Route as AuthenticatedSettingsTaxRatesRouteImport } from './routes/_authenticated/settings.tax-rates'
import { Route as AuthenticatedSettingsLocationsRouteImport } from './routes/_authenticated/settings.locations'
import { Route as AuthenticatedSettingsCategoriesRouteImport } from './routes/_authenticated/settings.categories'
import { Route as AuthenticatedSettingsBusinessRouteImport } from './routes/_authenticated/settings.business'
import { Route as AuthenticatedSettingsBrandsRouteImport } from './routes/_authenticated/settings.brands'
import { Route as AuthenticatedRestaurantTablesRouteImport } from './routes/_authenticated/restaurant.tables'
import { Route as AuthenticatedRestaurantOrdersRouteImport } from './routes/_authenticated/restaurant.orders'
import { Route as AuthenticatedReportsProfitRouteImport } from './routes/_authenticated/reports.profit'
import { Route as AuthenticatedReportsInventoryMovementRouteImport } from './routes/_authenticated/reports.inventory-movement'
import { Route as AuthenticatedReportsExpiryRouteImport } from './routes/_authenticated/reports.expiry'
import { Route as AuthenticatedReportsAnalyticsRouteImport } from './routes/_authenticated/reports.analytics'
import { Route as AuthenticatedRepairJobsRouteImport } from './routes/_authenticated/repair.jobs'
import { Route as AuthenticatedPurchasesNewRouteImport } from './routes/_authenticated/purchases.new'
import { Route as AuthenticatedPurchasesIdRouteImport } from './routes/_authenticated/purchases.$id'
import { Route as AuthenticatedProductsStockAdjustmentsRouteImport } from './routes/_authenticated/products.stock-adjustments'
import { Route as AuthenticatedProductsNewRouteImport } from './routes/_authenticated/products.new'
import { Route as AuthenticatedProductsIdRouteImport } from './routes/_authenticated/products.$id'
import { Route as AuthenticatedHrmPayrollRouteImport } from './routes/_authenticated/hrm.payroll'
import { Route as AuthenticatedHrmLeavesRouteImport } from './routes/_authenticated/hrm.leaves'
import { Route as AuthenticatedHrmEmployeesRouteImport } from './routes/_authenticated/hrm.employees'
import { Route as AuthenticatedHrmAttendanceRouteImport } from './routes/_authenticated/hrm.attendance'
import { Route as AuthenticatedCrmLeadsRouteImport } from './routes/_authenticated/crm.leads'
import { Route as AuthenticatedCrmFollowupsRouteImport } from './routes/_authenticated/crm.followups'
import { Route as AuthenticatedCrmCampaignsRouteImport } from './routes/_authenticated/crm.campaigns'
import { Route as AuthenticatedSalesIdEditRouteImport } from './routes/_authenticated/sales_.$id.edit'
import { Route as AuthenticatedPurchasesIdEditRouteImport } from './routes/_authenticated/purchases.$id.edit'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanSessionIdRoute = ScanSessionIdRouteImport.update({
  id: '/scan/$sessionId',
  path: '/scan/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSetupRoute = AuthenticatedSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalesRoute = AuthenticatedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRestaurantRoute = AuthenticatedRestaurantRouteImport.update({
  id: '/restaurant',
  path: '/restaurant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRepairRoute = AuthenticatedRepairRouteImport.update({
  id: '/repair',
  path: '/repair',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPurchasesRoute = AuthenticatedPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPosRoute = AuthenticatedPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManufacturingRoute =
  AuthenticatedManufacturingRouteImport.update({
    id: '/manufacturing',
    path: '/manufacturing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrmRoute = AuthenticatedHrmRouteImport.update({
  id: '/hrm',
  path: '/hrm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFilesRoute = AuthenticatedFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedRestaurantIndexRoute =
  AuthenticatedRestaurantIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRestaurantRoute,
  } as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedRepairIndexRoute =
  AuthenticatedRepairIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRepairRoute,
  } as any)
const AuthenticatedProductsIndexRoute =
  AuthenticatedProductsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProductsRoute,
  } as any)
const AuthenticatedHrmIndexRoute = AuthenticatedHrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedHrmRoute,
} as any)
const AuthenticatedCrmIndexRoute = AuthenticatedCrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedCrmRoute,
} as any)
const AuthenticatedSettingsUsersRoute =
  AuthenticatedSettingsUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsUnitsRoute =
  AuthenticatedSettingsUnitsRouteImport.update({
    id: '/units',
    path: '/units',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsTaxRatesRoute =
  AuthenticatedSettingsTaxRatesRouteImport.update({
    id: '/tax-rates',
    path: '/tax-rates',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsLocationsRoute =
  AuthenticatedSettingsLocationsRouteImport.update({
    id: '/locations',
    path: '/locations',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsCategoriesRoute =
  AuthenticatedSettingsCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsBusinessRoute =
  AuthenticatedSettingsBusinessRouteImport.update({
    id: '/business',
    path: '/business',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsBrandsRoute =
  AuthenticatedSettingsBrandsRouteImport.update({
    id: '/brands',
    path: '/brands',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedRestaurantTablesRoute =
  AuthenticatedRestaurantTablesRouteImport.update({
    id: '/tables',
    path: '/tables',
    getParentRoute: () => AuthenticatedRestaurantRoute,
  } as any)
const AuthenticatedRestaurantOrdersRoute =
  AuthenticatedRestaurantOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedRestaurantRoute,
  } as any)
const AuthenticatedReportsProfitRoute =
  AuthenticatedReportsProfitRouteImport.update({
    id: '/profit',
    path: '/profit',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsInventoryMovementRoute =
  AuthenticatedReportsInventoryMovementRouteImport.update({
    id: '/inventory-movement',
    path: '/inventory-movement',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsExpiryRoute =
  AuthenticatedReportsExpiryRouteImport.update({
    id: '/expiry',
    path: '/expiry',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsAnalyticsRoute =
  AuthenticatedReportsAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedRepairJobsRoute = AuthenticatedRepairJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedRepairRoute,
} as any)
const AuthenticatedPurchasesNewRoute =
  AuthenticatedPurchasesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedPurchasesRoute,
  } as any)
const AuthenticatedPurchasesIdRoute =
  AuthenticatedPurchasesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedPurchasesRoute,
  } as any)
const AuthenticatedProductsStockAdjustmentsRoute =
  AuthenticatedProductsStockAdjustmentsRouteImport.update({
    id: '/stock-adjustments',
    path: '/stock-adjustments',
    getParentRoute: () => AuthenticatedProductsRoute,
  } as any)
const AuthenticatedProductsNewRoute =
  AuthenticatedProductsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedProductsRoute,
  } as any)
const AuthenticatedProductsIdRoute = AuthenticatedProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedProductsRoute,
} as any)
const AuthenticatedHrmPayrollRoute = AuthenticatedHrmPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AuthenticatedHrmRoute,
} as any)
const AuthenticatedHrmLeavesRoute = AuthenticatedHrmLeavesRouteImport.update({
  id: '/leaves',
  path: '/leaves',
  getParentRoute: () => AuthenticatedHrmRoute,
} as any)
const AuthenticatedHrmEmployeesRoute =
  AuthenticatedHrmEmployeesRouteImport.update({
    id: '/employees',
    path: '/employees',
    getParentRoute: () => AuthenticatedHrmRoute,
  } as any)
const AuthenticatedHrmAttendanceRoute =
  AuthenticatedHrmAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AuthenticatedHrmRoute,
  } as any)
const AuthenticatedCrmLeadsRoute = AuthenticatedCrmLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedCrmRoute,
} as any)
const AuthenticatedCrmFollowupsRoute =
  AuthenticatedCrmFollowupsRouteImport.update({
    id: '/followups',
    path: '/followups',
    getParentRoute: () => AuthenticatedCrmRoute,
  } as any)
const AuthenticatedCrmCampaignsRoute =
  AuthenticatedCrmCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => AuthenticatedCrmRoute,
  } as any)
const AuthenticatedSalesIdEditRoute =
  AuthenticatedSalesIdEditRouteImport.update({
    id: '/sales_/$id/edit',
    path: '/sales/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchasesIdEditRoute =
  AuthenticatedPurchasesIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedPurchasesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/crm': typeof AuthenticatedCrmRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/files': typeof AuthenticatedFilesRoute
  '/hrm': typeof AuthenticatedHrmRouteWithChildren
  '/manufacturing': typeof AuthenticatedManufacturingRoute
  '/pos': typeof AuthenticatedPosRoute
  '/products': typeof AuthenticatedProductsRouteWithChildren
  '/purchases': typeof AuthenticatedPurchasesRouteWithChildren
  '/repair': typeof AuthenticatedRepairRouteWithChildren
  '/reports': typeof AuthenticatedReportsRouteWithChildren
  '/restaurant': typeof AuthenticatedRestaurantRouteWithChildren
  '/sales': typeof AuthenticatedSalesRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/setup': typeof AuthenticatedSetupRoute
  '/scan/$sessionId': typeof ScanSessionIdRoute
  '/crm/campaigns': typeof AuthenticatedCrmCampaignsRoute
  '/crm/followups': typeof AuthenticatedCrmFollowupsRoute
  '/crm/leads': typeof AuthenticatedCrmLeadsRoute
  '/hrm/attendance': typeof AuthenticatedHrmAttendanceRoute
  '/hrm/employees': typeof AuthenticatedHrmEmployeesRoute
  '/hrm/leaves': typeof AuthenticatedHrmLeavesRoute
  '/hrm/payroll': typeof AuthenticatedHrmPayrollRoute
  '/products/$id': typeof AuthenticatedProductsIdRoute
  '/products/new': typeof AuthenticatedProductsNewRoute
  '/products/stock-adjustments': typeof AuthenticatedProductsStockAdjustmentsRoute
  '/purchases/$id': typeof AuthenticatedPurchasesIdRouteWithChildren
  '/purchases/new': typeof AuthenticatedPurchasesNewRoute
  '/repair/jobs': typeof AuthenticatedRepairJobsRoute
  '/reports/analytics': typeof AuthenticatedReportsAnalyticsRoute
  '/reports/expiry': typeof AuthenticatedReportsExpiryRoute
  '/reports/inventory-movement': typeof AuthenticatedReportsInventoryMovementRoute
  '/reports/profit': typeof AuthenticatedReportsProfitRoute
  '/restaurant/orders': typeof AuthenticatedRestaurantOrdersRoute
  '/restaurant/tables': typeof AuthenticatedRestaurantTablesRoute
  '/settings/brands': typeof AuthenticatedSettingsBrandsRoute
  '/settings/business': typeof AuthenticatedSettingsBusinessRoute
  '/settings/categories': typeof AuthenticatedSettingsCategoriesRoute
  '/settings/locations': typeof AuthenticatedSettingsLocationsRoute
  '/settings/tax-rates': typeof AuthenticatedSettingsTaxRatesRoute
  '/settings/units': typeof AuthenticatedSettingsUnitsRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/crm/': typeof AuthenticatedCrmIndexRoute
  '/hrm/': typeof AuthenticatedHrmIndexRoute
  '/products/': typeof AuthenticatedProductsIndexRoute
  '/repair/': typeof AuthenticatedRepairIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/restaurant/': typeof AuthenticatedRestaurantIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/purchases/$id/edit': typeof AuthenticatedPurchasesIdEditRoute
  '/sales/$id/edit': typeof AuthenticatedSalesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/files': typeof AuthenticatedFilesRoute
  '/manufacturing': typeof AuthenticatedManufacturingRoute
  '/pos': typeof AuthenticatedPosRoute
  '/purchases': typeof AuthenticatedPurchasesRouteWithChildren
  '/sales': typeof AuthenticatedSalesRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/scan/$sessionId': typeof ScanSessionIdRoute
  '/crm/campaigns': typeof AuthenticatedCrmCampaignsRoute
  '/crm/followups': typeof AuthenticatedCrmFollowupsRoute
  '/crm/leads': typeof AuthenticatedCrmLeadsRoute
  '/hrm/attendance': typeof AuthenticatedHrmAttendanceRoute
  '/hrm/employees': typeof AuthenticatedHrmEmployeesRoute
  '/hrm/leaves': typeof AuthenticatedHrmLeavesRoute
  '/hrm/payroll': typeof AuthenticatedHrmPayrollRoute
  '/products/$id': typeof AuthenticatedProductsIdRoute
  '/products/new': typeof AuthenticatedProductsNewRoute
  '/products/stock-adjustments': typeof AuthenticatedProductsStockAdjustmentsRoute
  '/purchases/$id': typeof AuthenticatedPurchasesIdRouteWithChildren
  '/purchases/new': typeof AuthenticatedPurchasesNewRoute
  '/repair/jobs': typeof AuthenticatedRepairJobsRoute
  '/reports/analytics': typeof AuthenticatedReportsAnalyticsRoute
  '/reports/expiry': typeof AuthenticatedReportsExpiryRoute
  '/reports/inventory-movement': typeof AuthenticatedReportsInventoryMovementRoute
  '/reports/profit': typeof AuthenticatedReportsProfitRoute
  '/restaurant/orders': typeof AuthenticatedRestaurantOrdersRoute
  '/restaurant/tables': typeof AuthenticatedRestaurantTablesRoute
  '/settings/brands': typeof AuthenticatedSettingsBrandsRoute
  '/settings/business': typeof AuthenticatedSettingsBusinessRoute
  '/settings/categories': typeof AuthenticatedSettingsCategoriesRoute
  '/settings/locations': typeof AuthenticatedSettingsLocationsRoute
  '/settings/tax-rates': typeof AuthenticatedSettingsTaxRatesRoute
  '/settings/units': typeof AuthenticatedSettingsUnitsRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/crm': typeof AuthenticatedCrmIndexRoute
  '/hrm': typeof AuthenticatedHrmIndexRoute
  '/products': typeof AuthenticatedProductsIndexRoute
  '/repair': typeof AuthenticatedRepairIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/restaurant': typeof AuthenticatedRestaurantIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/purchases/$id/edit': typeof AuthenticatedPurchasesIdEditRoute
  '/sales/$id/edit': typeof AuthenticatedSalesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/files': typeof AuthenticatedFilesRoute
  '/_authenticated/hrm': typeof AuthenticatedHrmRouteWithChildren
  '/_authenticated/manufacturing': typeof AuthenticatedManufacturingRoute
  '/_authenticated/pos': typeof AuthenticatedPosRoute
  '/_authenticated/products': typeof AuthenticatedProductsRouteWithChildren
  '/_authenticated/purchases': typeof AuthenticatedPurchasesRouteWithChildren
  '/_authenticated/repair': typeof AuthenticatedRepairRouteWithChildren
  '/_authenticated/reports': typeof AuthenticatedReportsRouteWithChildren
  '/_authenticated/restaurant': typeof AuthenticatedRestaurantRouteWithChildren
  '/_authenticated/sales': typeof AuthenticatedSalesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/setup': typeof AuthenticatedSetupRoute
  '/scan/$sessionId': typeof ScanSessionIdRoute
  '/_authenticated/crm/campaigns': typeof AuthenticatedCrmCampaignsRoute
  '/_authenticated/crm/followups': typeof AuthenticatedCrmFollowupsRoute
  '/_authenticated/crm/leads': typeof AuthenticatedCrmLeadsRoute
  '/_authenticated/hrm/attendance': typeof AuthenticatedHrmAttendanceRoute
  '/_authenticated/hrm/employees': typeof AuthenticatedHrmEmployeesRoute
  '/_authenticated/hrm/leaves': typeof AuthenticatedHrmLeavesRoute
  '/_authenticated/hrm/payroll': typeof AuthenticatedHrmPayrollRoute
  '/_authenticated/products/$id': typeof AuthenticatedProductsIdRoute
  '/_authenticated/products/new': typeof AuthenticatedProductsNewRoute
  '/_authenticated/products/stock-adjustments': typeof AuthenticatedProductsStockAdjustmentsRoute
  '/_authenticated/purchases/$id': typeof AuthenticatedPurchasesIdRouteWithChildren
  '/_authenticated/purchases/new': typeof AuthenticatedPurchasesNewRoute
  '/_authenticated/repair/jobs': typeof AuthenticatedRepairJobsRoute
  '/_authenticated/reports/analytics': typeof AuthenticatedReportsAnalyticsRoute
  '/_authenticated/reports/expiry': typeof AuthenticatedReportsExpiryRoute
  '/_authenticated/reports/inventory-movement': typeof AuthenticatedReportsInventoryMovementRoute
  '/_authenticated/reports/profit': typeof AuthenticatedReportsProfitRoute
  '/_authenticated/restaurant/orders': typeof AuthenticatedRestaurantOrdersRoute
  '/_authenticated/restaurant/tables': typeof AuthenticatedRestaurantTablesRoute
  '/_authenticated/settings/brands': typeof AuthenticatedSettingsBrandsRoute
  '/_authenticated/settings/business': typeof AuthenticatedSettingsBusinessRoute
  '/_authenticated/settings/categories': typeof AuthenticatedSettingsCategoriesRoute
  '/_authenticated/settings/locations': typeof AuthenticatedSettingsLocationsRoute
  '/_authenticated/settings/tax-rates': typeof AuthenticatedSettingsTaxRatesRoute
  '/_authenticated/settings/units': typeof AuthenticatedSettingsUnitsRoute
  '/_authenticated/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/_authenticated/crm/': typeof AuthenticatedCrmIndexRoute
  '/_authenticated/hrm/': typeof AuthenticatedHrmIndexRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexRoute
  '/_authenticated/repair/': typeof AuthenticatedRepairIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/restaurant/': typeof AuthenticatedRestaurantIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/purchases/$id/edit': typeof AuthenticatedPurchasesIdEditRoute
  '/_authenticated/sales_/$id/edit': typeof AuthenticatedSalesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contacts'
    | '/crm'
    | '/dashboard'
    | '/expenses'
    | '/files'
    | '/hrm'
    | '/manufacturing'
    | '/pos'
    | '/products'
    | '/purchases'
    | '/repair'
    | '/reports'
    | '/restaurant'
    | '/sales'
    | '/settings'
    | '/setup'
    | '/scan/$sessionId'
    | '/crm/campaigns'
    | '/crm/followups'
    | '/crm/leads'
    | '/hrm/attendance'
    | '/hrm/employees'
    | '/hrm/leaves'
    | '/hrm/payroll'
    | '/products/$id'
    | '/products/new'
    | '/products/stock-adjustments'
    | '/purchases/$id'
    | '/purchases/new'
    | '/repair/jobs'
    | '/reports/analytics'
    | '/reports/expiry'
    | '/reports/inventory-movement'
    | '/reports/profit'
    | '/restaurant/orders'
    | '/restaurant/tables'
    | '/settings/brands'
    | '/settings/business'
    | '/settings/categories'
    | '/settings/locations'
    | '/settings/tax-rates'
    | '/settings/units'
    | '/settings/users'
    | '/crm/'
    | '/hrm/'
    | '/products/'
    | '/repair/'
    | '/reports/'
    | '/restaurant/'
    | '/settings/'
    | '/purchases/$id/edit'
    | '/sales/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contacts'
    | '/dashboard'
    | '/expenses'
    | '/files'
    | '/manufacturing'
    | '/pos'
    | '/purchases'
    | '/sales'
    | '/setup'
    | '/scan/$sessionId'
    | '/crm/campaigns'
    | '/crm/followups'
    | '/crm/leads'
    | '/hrm/attendance'
    | '/hrm/employees'
    | '/hrm/leaves'
    | '/hrm/payroll'
    | '/products/$id'
    | '/products/new'
    | '/products/stock-adjustments'
    | '/purchases/$id'
    | '/purchases/new'
    | '/repair/jobs'
    | '/reports/analytics'
    | '/reports/expiry'
    | '/reports/inventory-movement'
    | '/reports/profit'
    | '/restaurant/orders'
    | '/restaurant/tables'
    | '/settings/brands'
    | '/settings/business'
    | '/settings/categories'
    | '/settings/locations'
    | '/settings/tax-rates'
    | '/settings/units'
    | '/settings/users'
    | '/crm'
    | '/hrm'
    | '/products'
    | '/repair'
    | '/reports'
    | '/restaurant'
    | '/settings'
    | '/purchases/$id/edit'
    | '/sales/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/contacts'
    | '/_authenticated/crm'
    | '/_authenticated/dashboard'
    | '/_authenticated/expenses'
    | '/_authenticated/files'
    | '/_authenticated/hrm'
    | '/_authenticated/manufacturing'
    | '/_authenticated/pos'
    | '/_authenticated/products'
    | '/_authenticated/purchases'
    | '/_authenticated/repair'
    | '/_authenticated/reports'
    | '/_authenticated/restaurant'
    | '/_authenticated/sales'
    | '/_authenticated/settings'
    | '/_authenticated/setup'
    | '/scan/$sessionId'
    | '/_authenticated/crm/campaigns'
    | '/_authenticated/crm/followups'
    | '/_authenticated/crm/leads'
    | '/_authenticated/hrm/attendance'
    | '/_authenticated/hrm/employees'
    | '/_authenticated/hrm/leaves'
    | '/_authenticated/hrm/payroll'
    | '/_authenticated/products/$id'
    | '/_authenticated/products/new'
    | '/_authenticated/products/stock-adjustments'
    | '/_authenticated/purchases/$id'
    | '/_authenticated/purchases/new'
    | '/_authenticated/repair/jobs'
    | '/_authenticated/reports/analytics'
    | '/_authenticated/reports/expiry'
    | '/_authenticated/reports/inventory-movement'
    | '/_authenticated/reports/profit'
    | '/_authenticated/restaurant/orders'
    | '/_authenticated/restaurant/tables'
    | '/_authenticated/settings/brands'
    | '/_authenticated/settings/business'
    | '/_authenticated/settings/categories'
    | '/_authenticated/settings/locations'
    | '/_authenticated/settings/tax-rates'
    | '/_authenticated/settings/units'
    | '/_authenticated/settings/users'
    | '/_authenticated/crm/'
    | '/_authenticated/hrm/'
    | '/_authenticated/products/'
    | '/_authenticated/repair/'
    | '/_authenticated/reports/'
    | '/_authenticated/restaurant/'
    | '/_authenticated/settings/'
    | '/_authenticated/purchases/$id/edit'
    | '/_authenticated/sales_/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ScanSessionIdRoute: typeof ScanSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/$sessionId': {
      id: '/scan/$sessionId'
      path: '/scan/$sessionId'
      fullPath: '/scan/$sessionId'
      preLoaderRoute: typeof ScanSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/setup': {
      id: '/_authenticated/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthenticatedSetupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales': {
      id: '/_authenticated/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/restaurant': {
      id: '/_authenticated/restaurant'
      path: '/restaurant'
      fullPath: '/restaurant'
      preLoaderRoute: typeof AuthenticatedRestaurantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/repair': {
      id: '/_authenticated/repair'
      path: '/repair'
      fullPath: '/repair'
      preLoaderRoute: typeof AuthenticatedRepairRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchases': {
      id: '/_authenticated/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof AuthenticatedPurchasesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pos': {
      id: '/_authenticated/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AuthenticatedPosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manufacturing': {
      id: '/_authenticated/manufacturing'
      path: '/manufacturing'
      fullPath: '/manufacturing'
      preLoaderRoute: typeof AuthenticatedManufacturingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hrm': {
      id: '/_authenticated/hrm'
      path: '/hrm'
      fullPath: '/hrm'
      preLoaderRoute: typeof AuthenticatedHrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/files': {
      id: '/_authenticated/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof AuthenticatedFilesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/restaurant/': {
      id: '/_authenticated/restaurant/'
      path: '/'
      fullPath: '/restaurant/'
      preLoaderRoute: typeof AuthenticatedRestaurantIndexRouteImport
      parentRoute: typeof AuthenticatedRestaurantRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/repair/': {
      id: '/_authenticated/repair/'
      path: '/'
      fullPath: '/repair/'
      preLoaderRoute: typeof AuthenticatedRepairIndexRouteImport
      parentRoute: typeof AuthenticatedRepairRoute
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthenticatedProductsIndexRouteImport
      parentRoute: typeof AuthenticatedProductsRoute
    }
    '/_authenticated/hrm/': {
      id: '/_authenticated/hrm/'
      path: '/'
      fullPath: '/hrm/'
      preLoaderRoute: typeof AuthenticatedHrmIndexRouteImport
      parentRoute: typeof AuthenticatedHrmRoute
    }
    '/_authenticated/crm/': {
      id: '/_authenticated/crm/'
      path: '/'
      fullPath: '/crm/'
      preLoaderRoute: typeof AuthenticatedCrmIndexRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/settings/users': {
      id: '/_authenticated/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthenticatedSettingsUsersRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/units': {
      id: '/_authenticated/settings/units'
      path: '/units'
      fullPath: '/settings/units'
      preLoaderRoute: typeof AuthenticatedSettingsUnitsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/tax-rates': {
      id: '/_authenticated/settings/tax-rates'
      path: '/tax-rates'
      fullPath: '/settings/tax-rates'
      preLoaderRoute: typeof AuthenticatedSettingsTaxRatesRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/locations': {
      id: '/_authenticated/settings/locations'
      path: '/locations'
      fullPath: '/settings/locations'
      preLoaderRoute: typeof AuthenticatedSettingsLocationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/categories': {
      id: '/_authenticated/settings/categories'
      path: '/categories'
      fullPath: '/settings/categories'
      preLoaderRoute: typeof AuthenticatedSettingsCategoriesRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/business': {
      id: '/_authenticated/settings/business'
      path: '/business'
      fullPath: '/settings/business'
      preLoaderRoute: typeof AuthenticatedSettingsBusinessRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/brands': {
      id: '/_authenticated/settings/brands'
      path: '/brands'
      fullPath: '/settings/brands'
      preLoaderRoute: typeof AuthenticatedSettingsBrandsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/restaurant/tables': {
      id: '/_authenticated/restaurant/tables'
      path: '/tables'
      fullPath: '/restaurant/tables'
      preLoaderRoute: typeof AuthenticatedRestaurantTablesRouteImport
      parentRoute: typeof AuthenticatedRestaurantRoute
    }
    '/_authenticated/restaurant/orders': {
      id: '/_authenticated/restaurant/orders'
      path: '/orders'
      fullPath: '/restaurant/orders'
      preLoaderRoute: typeof AuthenticatedRestaurantOrdersRouteImport
      parentRoute: typeof AuthenticatedRestaurantRoute
    }
    '/_authenticated/reports/profit': {
      id: '/_authenticated/reports/profit'
      path: '/profit'
      fullPath: '/reports/profit'
      preLoaderRoute: typeof AuthenticatedReportsProfitRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/inventory-movement': {
      id: '/_authenticated/reports/inventory-movement'
      path: '/inventory-movement'
      fullPath: '/reports/inventory-movement'
      preLoaderRoute: typeof AuthenticatedReportsInventoryMovementRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/expiry': {
      id: '/_authenticated/reports/expiry'
      path: '/expiry'
      fullPath: '/reports/expiry'
      preLoaderRoute: typeof AuthenticatedReportsExpiryRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/analytics': {
      id: '/_authenticated/reports/analytics'
      path: '/analytics'
      fullPath: '/reports/analytics'
      preLoaderRoute: typeof AuthenticatedReportsAnalyticsRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/repair/jobs': {
      id: '/_authenticated/repair/jobs'
      path: '/jobs'
      fullPath: '/repair/jobs'
      preLoaderRoute: typeof AuthenticatedRepairJobsRouteImport
      parentRoute: typeof AuthenticatedRepairRoute
    }
    '/_authenticated/purchases/new': {
      id: '/_authenticated/purchases/new'
      path: '/new'
      fullPath: '/purchases/new'
      preLoaderRoute: typeof AuthenticatedPurchasesNewRouteImport
      parentRoute: typeof AuthenticatedPurchasesRoute
    }
    '/_authenticated/purchases/$id': {
      id: '/_authenticated/purchases/$id'
      path: '/$id'
      fullPath: '/purchases/$id'
      preLoaderRoute: typeof AuthenticatedPurchasesIdRouteImport
      parentRoute: typeof AuthenticatedPurchasesRoute
    }
    '/_authenticated/products/stock-adjustments': {
      id: '/_authenticated/products/stock-adjustments'
      path: '/stock-adjustments'
      fullPath: '/products/stock-adjustments'
      preLoaderRoute: typeof AuthenticatedProductsStockAdjustmentsRouteImport
      parentRoute: typeof AuthenticatedProductsRoute
    }
    '/_authenticated/products/new': {
      id: '/_authenticated/products/new'
      path: '/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AuthenticatedProductsNewRouteImport
      parentRoute: typeof AuthenticatedProductsRoute
    }
    '/_authenticated/products/$id': {
      id: '/_authenticated/products/$id'
      path: '/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof AuthenticatedProductsIdRouteImport
      parentRoute: typeof AuthenticatedProductsRoute
    }
    '/_authenticated/hrm/payroll': {
      id: '/_authenticated/hrm/payroll'
      path: '/payroll'
      fullPath: '/hrm/payroll'
      preLoaderRoute: typeof AuthenticatedHrmPayrollRouteImport
      parentRoute: typeof AuthenticatedHrmRoute
    }
    '/_authenticated/hrm/leaves': {
      id: '/_authenticated/hrm/leaves'
      path: '/leaves'
      fullPath: '/hrm/leaves'
      preLoaderRoute: typeof AuthenticatedHrmLeavesRouteImport
      parentRoute: typeof AuthenticatedHrmRoute
    }
    '/_authenticated/hrm/employees': {
      id: '/_authenticated/hrm/employees'
      path: '/employees'
      fullPath: '/hrm/employees'
      preLoaderRoute: typeof AuthenticatedHrmEmployeesRouteImport
      parentRoute: typeof AuthenticatedHrmRoute
    }
    '/_authenticated/hrm/attendance': {
      id: '/_authenticated/hrm/attendance'
      path: '/attendance'
      fullPath: '/hrm/attendance'
      preLoaderRoute: typeof AuthenticatedHrmAttendanceRouteImport
      parentRoute: typeof AuthenticatedHrmRoute
    }
    '/_authenticated/crm/leads': {
      id: '/_authenticated/crm/leads'
      path: '/leads'
      fullPath: '/crm/leads'
      preLoaderRoute: typeof AuthenticatedCrmLeadsRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/followups': {
      id: '/_authenticated/crm/followups'
      path: '/followups'
      fullPath: '/crm/followups'
      preLoaderRoute: typeof AuthenticatedCrmFollowupsRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/campaigns': {
      id: '/_authenticated/crm/campaigns'
      path: '/campaigns'
      fullPath: '/crm/campaigns'
      preLoaderRoute: typeof AuthenticatedCrmCampaignsRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/sales_/$id/edit': {
      id: '/_authenticated/sales_/$id/edit'
      path: '/sales/$id/edit'
      fullPath: '/sales/$id/edit'
      preLoaderRoute: typeof AuthenticatedSalesIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchases/$id/edit': {
      id: '/_authenticated/purchases/$id/edit'
      path: '/edit'
      fullPath: '/purchases/$id/edit'
      preLoaderRoute: typeof AuthenticatedPurchasesIdEditRouteImport
      parentRoute: typeof AuthenticatedPurchasesIdRoute
    }
  }
}

interface AuthenticatedCrmRouteChildren {
  AuthenticatedCrmCampaignsRoute: typeof AuthenticatedCrmCampaignsRoute
  AuthenticatedCrmFollowupsRoute: typeof AuthenticatedCrmFollowupsRoute
  AuthenticatedCrmLeadsRoute: typeof AuthenticatedCrmLeadsRoute
  AuthenticatedCrmIndexRoute: typeof AuthenticatedCrmIndexRoute
}

const AuthenticatedCrmRouteChildren: AuthenticatedCrmRouteChildren = {
  AuthenticatedCrmCampaignsRoute: AuthenticatedCrmCampaignsRoute,
  AuthenticatedCrmFollowupsRoute: AuthenticatedCrmFollowupsRoute,
  AuthenticatedCrmLeadsRoute: AuthenticatedCrmLeadsRoute,
  AuthenticatedCrmIndexRoute: AuthenticatedCrmIndexRoute,
}

const AuthenticatedCrmRouteWithChildren =
  AuthenticatedCrmRoute._addFileChildren(AuthenticatedCrmRouteChildren)

interface AuthenticatedHrmRouteChildren {
  AuthenticatedHrmAttendanceRoute: typeof AuthenticatedHrmAttendanceRoute
  AuthenticatedHrmEmployeesRoute: typeof AuthenticatedHrmEmployeesRoute
  AuthenticatedHrmLeavesRoute: typeof AuthenticatedHrmLeavesRoute
  AuthenticatedHrmPayrollRoute: typeof AuthenticatedHrmPayrollRoute
  AuthenticatedHrmIndexRoute: typeof AuthenticatedHrmIndexRoute
}

const AuthenticatedHrmRouteChildren: AuthenticatedHrmRouteChildren = {
  AuthenticatedHrmAttendanceRoute: AuthenticatedHrmAttendanceRoute,
  AuthenticatedHrmEmployeesRoute: AuthenticatedHrmEmployeesRoute,
  AuthenticatedHrmLeavesRoute: AuthenticatedHrmLeavesRoute,
  AuthenticatedHrmPayrollRoute: AuthenticatedHrmPayrollRoute,
  AuthenticatedHrmIndexRoute: AuthenticatedHrmIndexRoute,
}

const AuthenticatedHrmRouteWithChildren =
  AuthenticatedHrmRoute._addFileChildren(AuthenticatedHrmRouteChildren)

interface AuthenticatedProductsRouteChildren {
  AuthenticatedProductsIdRoute: typeof AuthenticatedProductsIdRoute
  AuthenticatedProductsNewRoute: typeof AuthenticatedProductsNewRoute
  AuthenticatedProductsStockAdjustmentsRoute: typeof AuthenticatedProductsStockAdjustmentsRoute
  AuthenticatedProductsIndexRoute: typeof AuthenticatedProductsIndexRoute
}

const AuthenticatedProductsRouteChildren: AuthenticatedProductsRouteChildren = {
  AuthenticatedProductsIdRoute: AuthenticatedProductsIdRoute,
  AuthenticatedProductsNewRoute: AuthenticatedProductsNewRoute,
  AuthenticatedProductsStockAdjustmentsRoute:
    AuthenticatedProductsStockAdjustmentsRoute,
  AuthenticatedProductsIndexRoute: AuthenticatedProductsIndexRoute,
}

const AuthenticatedProductsRouteWithChildren =
  AuthenticatedProductsRoute._addFileChildren(
    AuthenticatedProductsRouteChildren,
  )

interface AuthenticatedPurchasesIdRouteChildren {
  AuthenticatedPurchasesIdEditRoute: typeof AuthenticatedPurchasesIdEditRoute
}

const AuthenticatedPurchasesIdRouteChildren: AuthenticatedPurchasesIdRouteChildren =
  {
    AuthenticatedPurchasesIdEditRoute: AuthenticatedPurchasesIdEditRoute,
  }

const AuthenticatedPurchasesIdRouteWithChildren =
  AuthenticatedPurchasesIdRoute._addFileChildren(
    AuthenticatedPurchasesIdRouteChildren,
  )

interface AuthenticatedPurchasesRouteChildren {
  AuthenticatedPurchasesIdRoute: typeof AuthenticatedPurchasesIdRouteWithChildren
  AuthenticatedPurchasesNewRoute: typeof AuthenticatedPurchasesNewRoute
}

const AuthenticatedPurchasesRouteChildren: AuthenticatedPurchasesRouteChildren =
  {
    AuthenticatedPurchasesIdRoute: AuthenticatedPurchasesIdRouteWithChildren,
    AuthenticatedPurchasesNewRoute: AuthenticatedPurchasesNewRoute,
  }

const AuthenticatedPurchasesRouteWithChildren =
  AuthenticatedPurchasesRoute._addFileChildren(
    AuthenticatedPurchasesRouteChildren,
  )

interface AuthenticatedRepairRouteChildren {
  AuthenticatedRepairJobsRoute: typeof AuthenticatedRepairJobsRoute
  AuthenticatedRepairIndexRoute: typeof AuthenticatedRepairIndexRoute
}

const AuthenticatedRepairRouteChildren: AuthenticatedRepairRouteChildren = {
  AuthenticatedRepairJobsRoute: AuthenticatedRepairJobsRoute,
  AuthenticatedRepairIndexRoute: AuthenticatedRepairIndexRoute,
}

const AuthenticatedRepairRouteWithChildren =
  AuthenticatedRepairRoute._addFileChildren(AuthenticatedRepairRouteChildren)

interface AuthenticatedReportsRouteChildren {
  AuthenticatedReportsAnalyticsRoute: typeof AuthenticatedReportsAnalyticsRoute
  AuthenticatedReportsExpiryRoute: typeof AuthenticatedReportsExpiryRoute
  AuthenticatedReportsInventoryMovementRoute: typeof AuthenticatedReportsInventoryMovementRoute
  AuthenticatedReportsProfitRoute: typeof AuthenticatedReportsProfitRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
}

const AuthenticatedReportsRouteChildren: AuthenticatedReportsRouteChildren = {
  AuthenticatedReportsAnalyticsRoute: AuthenticatedReportsAnalyticsRoute,
  AuthenticatedReportsExpiryRoute: AuthenticatedReportsExpiryRoute,
  AuthenticatedReportsInventoryMovementRoute:
    AuthenticatedReportsInventoryMovementRoute,
  AuthenticatedReportsProfitRoute: AuthenticatedReportsProfitRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
}

const AuthenticatedReportsRouteWithChildren =
  AuthenticatedReportsRoute._addFileChildren(AuthenticatedReportsRouteChildren)

interface AuthenticatedRestaurantRouteChildren {
  AuthenticatedRestaurantOrdersRoute: typeof AuthenticatedRestaurantOrdersRoute
  AuthenticatedRestaurantTablesRoute: typeof AuthenticatedRestaurantTablesRoute
  AuthenticatedRestaurantIndexRoute: typeof AuthenticatedRestaurantIndexRoute
}

const AuthenticatedRestaurantRouteChildren: AuthenticatedRestaurantRouteChildren =
  {
    AuthenticatedRestaurantOrdersRoute: AuthenticatedRestaurantOrdersRoute,
    AuthenticatedRestaurantTablesRoute: AuthenticatedRestaurantTablesRoute,
    AuthenticatedRestaurantIndexRoute: AuthenticatedRestaurantIndexRoute,
  }

const AuthenticatedRestaurantRouteWithChildren =
  AuthenticatedRestaurantRoute._addFileChildren(
    AuthenticatedRestaurantRouteChildren,
  )

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsBrandsRoute: typeof AuthenticatedSettingsBrandsRoute
  AuthenticatedSettingsBusinessRoute: typeof AuthenticatedSettingsBusinessRoute
  AuthenticatedSettingsCategoriesRoute: typeof AuthenticatedSettingsCategoriesRoute
  AuthenticatedSettingsLocationsRoute: typeof AuthenticatedSettingsLocationsRoute
  AuthenticatedSettingsTaxRatesRoute: typeof AuthenticatedSettingsTaxRatesRoute
  AuthenticatedSettingsUnitsRoute: typeof AuthenticatedSettingsUnitsRoute
  AuthenticatedSettingsUsersRoute: typeof AuthenticatedSettingsUsersRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsBrandsRoute: AuthenticatedSettingsBrandsRoute,
  AuthenticatedSettingsBusinessRoute: AuthenticatedSettingsBusinessRoute,
  AuthenticatedSettingsCategoriesRoute: AuthenticatedSettingsCategoriesRoute,
  AuthenticatedSettingsLocationsRoute: AuthenticatedSettingsLocationsRoute,
  AuthenticatedSettingsTaxRatesRoute: AuthenticatedSettingsTaxRatesRoute,
  AuthenticatedSettingsUnitsRoute: AuthenticatedSettingsUnitsRoute,
  AuthenticatedSettingsUsersRoute: AuthenticatedSettingsUsersRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedFilesRoute: typeof AuthenticatedFilesRoute
  AuthenticatedHrmRoute: typeof AuthenticatedHrmRouteWithChildren
  AuthenticatedManufacturingRoute: typeof AuthenticatedManufacturingRoute
  AuthenticatedPosRoute: typeof AuthenticatedPosRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRouteWithChildren
  AuthenticatedPurchasesRoute: typeof AuthenticatedPurchasesRouteWithChildren
  AuthenticatedRepairRoute: typeof AuthenticatedRepairRouteWithChildren
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRouteWithChildren
  AuthenticatedRestaurantRoute: typeof AuthenticatedRestaurantRouteWithChildren
  AuthenticatedSalesRoute: typeof AuthenticatedSalesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedSetupRoute: typeof AuthenticatedSetupRoute
  AuthenticatedSalesIdEditRoute: typeof AuthenticatedSalesIdEditRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedFilesRoute: AuthenticatedFilesRoute,
  AuthenticatedHrmRoute: AuthenticatedHrmRouteWithChildren,
  AuthenticatedManufacturingRoute: AuthenticatedManufacturingRoute,
  AuthenticatedPosRoute: AuthenticatedPosRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRouteWithChildren,
  AuthenticatedPurchasesRoute: AuthenticatedPurchasesRouteWithChildren,
  AuthenticatedRepairRoute: AuthenticatedRepairRouteWithChildren,
  AuthenticatedReportsRoute: AuthenticatedReportsRouteWithChildren,
  AuthenticatedRestaurantRoute: AuthenticatedRestaurantRouteWithChildren,
  AuthenticatedSalesRoute: AuthenticatedSalesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedSetupRoute: AuthenticatedSetupRoute,
  AuthenticatedSalesIdEditRoute: AuthenticatedSalesIdEditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ScanSessionIdRoute: ScanSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
