// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fmjzfzvbswkbxsrwcknu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtanpmenZic3drYnhzcndja251Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE5NzQwOTUsImV4cCI6MjA5NzU1MDA5NX0.Ck2sXgAYwggdKxePWSTJ5l0_dq3TWmrcO-uR787gdT0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});